# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{shoutcast_api}
  s.version = "0.1.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Suschlik"]
  s.date = %q{2009-12-17}
  s.default_executable = %q{shoutcast_search}
  s.email = %q{peter-scapi@suschlik.de}
  s.executables = ["shoutcast_search"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     ".watchr",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/shoutcast_search",
     "lib/shoutcast_api.rb",
     "shoutcast_api.gemspec",
     "test/fixtures/empty.plain",
     "test/fixtures/genrelist.plain",
     "test/fixtures/search_death.plain",
     "test/helper.rb",
     "test/test_basic.rb",
     "test/test_fetcher.rb",
     "test/test_xml.rb"
  ]
  s.homepage = %q{http://github.com/splattael/shoutcast_api}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple shoutcast.com API.}
  s.test_files = [
    "test/test_fetcher.rb",
     "test/test_basic.rb",
     "test/test_xml.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, ["~> 0.4"])
      s.add_runtime_dependency(%q<roxml>, ["~> 2.5"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<riot>, [">= 0"])
      s.add_development_dependency(%q<riot_notifier>, ["= 0.0.7"])
    else
      s.add_dependency(%q<httparty>, ["~> 0.4"])
      s.add_dependency(%q<roxml>, ["~> 2.5"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<riot>, [">= 0"])
      s.add_dependency(%q<riot_notifier>, ["= 0.0.7"])
    end
  else
    s.add_dependency(%q<httparty>, ["~> 0.4"])
    s.add_dependency(%q<roxml>, ["~> 2.5"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<riot>, [">= 0"])
    s.add_dependency(%q<riot_notifier>, ["= 0.0.7"])
  end
end

